# Generated by Django 5.2.4 on 2025-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('title_normalized', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_normalized', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(unique=True)),
                ('movies', models.ManyToManyField(related_name='actors', to='csfd.movie')),
            ],
        ),
    ]
